stages:
  - test

# Cache libraries in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - vendor/

# PHP 7.4 
test:7.4:
  stage: test
  image: ecmchow/ubuntu-php:focal-7.4
  script:
    - bash
    - service redis-server restart
    - chmod -R +x tools
    - composer install
    - tools/php-cs-fixer-v3.phar fix Core --using-cache=no --diff --dry-run --verbose
    - tools/php-cs-fixer-v3.phar fix start-mailer.php --using-cache=no --diff --dry-run --verbose
    - php tools/phpunit-9.5.phar --testsuite core-units
    - openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout test/selfsigned.key -out test/selfsigned.crt
    - composer run ci-e2e && sleep 0.1
    - cat test/e2e.log
    - cat test/e2e-redis.log
    - composer run build
    - chmod +x dist/smtp-mailer.phar
    - composer run ci-build && sleep 0.1
    - cat test/build.log
    - cat test/build-redis.log
  rules:
    - changes:
      - '**.env'
      - '**.phar'
      - '**.php'
      - '**.sh'
      - '**.json'
      - '**.xml'
      - '**.yml'

# PHP 8.1
test:8.1:
  stage: test
  image: ecmchow/ubuntu-php:focal-8.1
  script:
    - bash
    - service redis-server restart
    - chmod -R +x tools
    - composer install
    - tools/php-cs-fixer-v3.phar fix Core --using-cache=no --diff --dry-run --verbose
    - tools/php-cs-fixer-v3.phar fix start-mailer.php --using-cache=no --diff --dry-run --verbose
    - php tools/phpunit-9.5.phar --testsuite core-units
    - openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout test/selfsigned.key -out test/selfsigned.crt
    - composer run ci-e2e && sleep 0.1
    - cat test/e2e.log
    - cat test/e2e-redis.log
    - composer run build
    - chmod +x dist/smtp-mailer.phar
    - composer run ci-build && sleep 0.1
    - cat test/build.log
    - cat test/build-redis.log
  rules:
    - changes:
      - '**.env'
      - '**.phar'
      - '**.php'
      - '**.sh'
      - '**.json'
      - '**.xml'
      - '**.yml'